### ISSUE TITLE
Circles are being cut on Mobile Landscape

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/01som#13]
This is happening both on an Android phone and on an iPad, as you can see in the following pictures.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4632023/34939527-00cde07a-f9e4-11e7-986b-934ccb5ba9d6.png">
![screenshot_20180115-105529](https://user-images.githubusercontent.com/4632023/34939528-00e808ba-f9e4-11e7-8f85-494d969a8ffb.jpg)
![screenshot_20180115-105543](https://user-images.githubusercontent.com/4632023/34939529-01015bc6-f9e4-11e7-8ecd-3fc4c77a747b.jpg)

**Comment by nunoh** [comment]
Closing as this is not happening as of now. True, that some scroll is needed to see the full page, but that's usable and no circle is being cut.
