### ISSUE TITLE
Include basic instructions for each website

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/01som#4]
Ideally, it should choose to display them either in portuguese or in english according to browser language.

- [x] Ritmo
- [x] Ritmo e Melodia
- [ ] Sequenciador
- [ ] Canção
- [ ] Notação
- [ ] Acústica
- [ ] Teoria

**Comment by Oscar-Rodrigues** [comment]
Ritmo:

Clica nos círculos pequenos para escolher o som - uma vez para o azul, duas vezes para o verde, três vezes para o vermelho, quatro vezes para o branco.
Clica nos botões para escolher o andamento.

Click the small circles to choose the sound - once for blue, twice for green, three times for red and four times for white.
Click the buttons to choose the tempo.

**Comment by Oscar-Rodrigues** [comment]
Ritmo e Melodia:

Clica nos círculos pequenos para escolher o som: no instrumento azul, clica uma vez para o azul, duas vezes para o verde, três vezes para o vermelho, quatro vezes para o branco; no instrumento verde, escolhe as notas - dó grave, ré, mi, sol, lá e dó agudo.
Clica nos botões para escolher o andamento.

Click the small circles to choose the sound: in the blue instrument click once for blue, twice for green, three times for red and four times for white; in the green instrument, choose the notes - low c, d, e, g, a and high c.
Click the buttons to choose the tempo.

**Comment by nunoh** [comment]
Closing this as well, since we at least have the basic of instructions working already. Will keep improving as needed, but see no need for specific issue.
